
export const freelancers = [
    {
        id: 1,
        name: "Chanminea Houn",
        expertise: "Web Frontend Developer",
        category: "Frontend",
        location: "Phnom Penh",
        skills: [],
        profilePicture: "https://images.pexels.com/photos/3861958/pexels-photo-3861958.jpeg",
    },
    {
        id: 2,
        name: "Long Sophy",
        expertise: "Web Frontend Developer",
        category: "Frontend",
        location: "Phnom Penh",
        skills: [],
        profilePicture: "https://images.pexels.com/photos/982612/pexels-photo-982612.jpeg",
    },
    {
        id: 3,
        name: "Bun Chan Rainsy",
        expertise: "Backend Developer",
        category: "Backend",
        location: "Phnom Penh",
        skills: [],
        profilePicture: "https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg",
    },
    {
        id: 4,
        name: "Chantha Eang",
        expertise: "Web Frontend Developer",
        category: "Frontend",
        location: "Phnom Penh",
        skills: [],
        profilePicture: "https://images.pexels.com/photos/3861958/pexels-photo-3861958.jpeg",
    },
    {
        id: 5,
        name: "Rithy Vong Saravoun",
        expertise: "Web Backend Developer",
        category: "Backend",
        location: "Phnom Penh",
        skills: [],
        profilePicture:  "https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg",
    },
    {
        id: 6,
        name: "Sereysambat Sok",
        expertise: "Web Frontend Developer",
        category: "Frontend",
        location: "Phnom Penh",
        skills: [],
        profilePicture:  "https://images.pexels.com/photos/3861958/pexels-photo-3861958.jpeg",
    },
    {
        id: 7,
        name: "Makara Phon",
        expertise: "Web Frontend Developer",
        category: "Frontend",
        location: "Phnom Penh",
        skills: [],
        profilePicture:  "https://images.pexels.com/photos/3861958/pexels-photo-3861958.jpeg",
    },
    {
        id: 8,
        name: "Ouk Sok Reaksmey",
        expertise: "Web Frontend Developer",
        category: "Frontend",
        location: "Phnom Penh",
        skills: [],
        profilePicture:  "https://images.pexels.com/photos/3861958/pexels-photo-3861958.jpeg",
    },
    {
        id: 9,
        name: "Sophat Chhay",
        expertise: "Full Stack Developer",
        category: "Backend",
        location: "Phnom Penh",
        skills: ["NodeJS", "Python", "PHP"],
        profilePicture:  "https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg",
    },
];
